name: Test
on: [push]
jobs:
  run:
    name: Test
    runs-on:
        - ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.21.x
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest

      - name: GoReleaser
        run: goreleaser
        with:
          args: release --skip=publish --clean --snapshot