name: terraform-openprovider-releaser
on: [push]


jobs:
  run:
  
    name: terraform-openprovider-releaser
    runs-on:
        - ubuntu-latest

    steps:
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.21.x
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}